routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PostsApiController::class, 'postsWithoutAuth']);
Route::get('/post/{id}', [\App\Http\Controllers\PostsApiController::class, 'getByIdWithoutAuth'])->name('user_post.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::resource('posts', App\Http\Controllers\PostsApiController::class);
    Route::resource('users', App\Http\Controllers\UserApiController::class)->except('show');
    Route::resource('comment', App\Http\Controllers\CommentsController::class)->except('index', 'show');

});

resources/views/partials/comments_partial.blade.php
<div class="col-12 p-2">
    <div class="card">
        <div class="card-header mb-2">
            <h3 class="card-title">Komentarze</h3>
        </div>
        <div class="card-body table-responsive p-0 auto-height">
            @auth
                <form action="{{route('comment.create')}}">
                    <input name="post_id" type="text" hidden value="{{$post->id}}">
                    <button type="submit" class="btn-primary btn btn">Dodaj</button>
                </form>
            @endauth
            <table id="posts-table" class="table table-head-fixed text-nowrap">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Użytkownik</th>
                    <th>Email</th>
                    <th>Treść</th>
                    @auth
                        <th>
                            Edytuj
                        </th>
                        <th>
                            Usuń
                        </th>
                    @endauth
                    <th>Utworzono</th>
                    <th>Edytowano</th>
                </thead>
                <tbody>
                @foreach($post->comments()->get() as $comment)
                    <tr>
                        <td class="id"><label>{{$loop->iteration}}</label></td>
                        <td class="user"><label>{{$comment->name}}</label></td>
                        <td class="email"><label>{{$comment->email}}</label></td>
                        <td class="body"><label>{!! nl2br($comment->body) !!}</label></td>
                        @auth
                            <td class="edit_user">
                                <a href="{{route('comment.edit',$comment)}}" class="btn-warning btn">Edytuj</a>
                            </td>
                            <td class="delete_user">
                                <form action="{{route('comment.destroy',$comment)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-danger btn">Usuń</button>
                                </form>
                            </td>
                        @endauth
                        <td class="created_at"><label>{{$comment->created_at}}</label></td>
                        <td class="updated_at"><label>{{$comment->updated_at}}</label></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/partials/flash-messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Please check the form below for errors
    </div>
@endif

resources/views/partials/post_partial.blade.php
<div class="col-12 p-2">
    <div class="card card-warning">
        <div class="card-header ">
            <h3 class="card-title"><b>Temat</b> : {{$post->title}}</h3>
        </div>
        <div class="card-header mb-2">
            <h7><b>Użytkownik</b> : {{$post->user()->username}}</h7>
        </div>
        <div class="card-body table-responsive p-0 auto-height ">
            <div class="container">
                {{$post->body}}
            </div>
        </div>
    </div>
</div>

resources/views/partials/post_table_partial.blade.php
<div class="col-12 p-2">
    <div class="card">
        <div class="card-header mb-2">
            <h3 class="card-title">Posty</h3>
        </div>
        <div class="card-body table-responsive p-0 auto-height">
            <table id="posts-table" class="table table-head-fixed text-nowrap">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Post</th>
                    <th>Autor</th>
                    @auth
                        <th>
                            Edytuj
                        </th>
                        <th>
                            Usuń
                        </th>
                    @endauth
                    <th>Utworzono</th>
                    <th>Edytowano</th>
                </thead>
                <tbody>
                @foreach($posts as $post)
                    <tr>
                        <td class="id"><label>{{$post->id}}</label></td>
                        <td class="post_id"><label><a href="
                                @Auth
                                {{route('posts.show',$post->id)}}
                                @else
                                {{route('user_post.show',$post->id)}}
                                @endif
                                    ">{{$post->title}}</a></label></td>
                        <td class="user"><label>
                                {{$post->user()->username}}
                            </label>
                        </td>
                        @auth
                            <td class="edit_user">
                                <a href="{{route('posts.edit',$post)}}" class="btn-warning btn">Edytuj</a>
                            </td>
                            <td class="delete_user">
                                <form action="{{route('posts.destroy',$post)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-danger btn">Usuń</button>
                                </form>
                            </td>
                        @endauth
                        <td class="created_at"><label>{{$post->created_at}}</label></td>
                        <td class="updated_at"><label>{{$post->updated_at}}</label></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $posts->links() }}
        </div>
    </div>
</div>