routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PostsApiController::class, 'postsWithoutAuth']);
Route::get('/post/{id}', [\App\Http\Controllers\PostsApiController::class, 'getByIdWithoutAuth'])->name('user_post.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::resource('posts', App\Http\Controllers\PostsApiController::class);
    Route::resource('users', App\Http\Controllers\UserApiController::class)->except('show');
    Route::resource('comment', App\Http\Controllers\CommentsController::class)->except('index', 'show');

});

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\CommentApi;
use App\Models\CompanyApi;
use App\Models\PostApi;
use App\Models\UserApi;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    public function edit(Request $request, $comment)
    {
        $comment = CommentApi::find($comment);
        return view('admin.comments.edit', [
            'comment' => $comment,
            'post' => $comment->post()
        ]);
    }

    public function update(Request $request, $comment)
    {
        $commentInputs = $request->only('body', 'name', 'email');
        $commentDB = CommentApi::find($comment);
        if ($commentDB) {
            $commentDB->name = $commentInputs['name'];
            $commentDB->body = $commentInputs['body'];
            $commentDB->email = $commentInputs['email'];
            $commentDB->save();
            return redirect()->route('posts.show', $commentDB->post_id)->with('success', 'Zaktualizowano komentarz!');
        }
        return redirect()->route('posts.index')->with('error', 'Wystąpił błąd');

    }

    public function create(Request $request)
    {
        return view('admin.comments.create', [
            'post' => PostApi::find($request->get('post_id'))
        ]);
    }

    public function store(Request $request)
    {
        $commentInputs = $request->only('post_id', 'name', 'email', 'body');
        $commentDB = CommentApi::create($commentInputs);
        if ($commentDB) {
            $commentDB->body = $commentInputs['body'];
            $commentDB->save();
            return redirect()->route('posts.show', PostApi::find($commentInputs['post_id']))->with('success', 'Dodano komentarz!');
        }
        return redirect()->route('posts.index')->with('error', 'Wystąpił błąd');

    }

    public function destroy(Request $request, $id)
    {
        $comment = CommentApi::find($id);
        $post = $comment->post();
        try {
            $comment->delete();
            $result = ['status' => 'success', 'message' => 'Usunięto komentarz!'];
        } catch (Exception $e) {
            $result = ['status' => 'error', 'message' => 'Wystąpił błąd!'];
        }
        return redirect()->route('posts.show', $post)->with($result['status'], $result['message']);
    }
}

resources/views/admin/comments/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-2">
                @include('partials.flash-messages')

                <form action="{{ route('comment.store') }}" method="POST">
                    @csrf
                    @include('admin.comments.partials.partial_create_edit')
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Zapisz</button>
                    </div>
                </form>
                <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
                    <h1>Post</h1>
                    @include('partials.post_partial')
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
@stop

resources/views/admin/comments/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-2">
                @include('partials.flash-messages')

                <form action="{{ route('comment.update', $post) }}" method="POST">
                    @csrf
                    @method('put')
                    @include('admin.comments.partials.partial_create_edit')
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Edytuj</button>
                    </div>
                </form>
                <h1>Post</h1>
                <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
                    @include('partials.post_partial')
                </div>
            </div>
        </div>

    </div>
@stop
@section('js')
@stop