routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PostsApiController::class, 'postsWithoutAuth']);
Route::get('/post/{id}', [\App\Http\Controllers\PostsApiController::class, 'getByIdWithoutAuth'])->name('user_post.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::resource('posts', App\Http\Controllers\PostsApiController::class);
    Route::resource('users', App\Http\Controllers\UserApiController::class)->except('show');
    Route::resource('comment', App\Http\Controllers\CommentsController::class)->except('index', 'show');

});

resources/views/admin/posts/create.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-2">
                @include('partials.flash-messages')

                <form action="{{ route('posts.store') }}" method="POST">
                    @csrf
                    @include('admin.posts.partials.partial_create_edit')
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Zapisz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop
@section('js')
@stop

resources/views/admin/posts/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-2">
                @include('partials.flash-messages')

                <form action="{{ route('posts.update', $post) }}" method="POST">
                    @csrf
                    @method('put')
                    @include('admin.posts.partials.partial_create_edit')
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Edytuj</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop
@section('js')
@stop

resources/views/admin/posts/index.blade.php
@extends('adminlte::page')

@section('css')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css"/>
@endsection

@section('content')
    @include('partials.flash-messages')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <h1>Posty</h1>
        @include('partials.post_table_partial')
    </div>
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
{{--
    <script src="{{ asset('js/datatables.js') }}"></script>
--}}
@endsection

resources/views/admin/posts/show.blade.php
@extends('adminlte::page')

@section('css')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css"/>
@endsection

@section('content')
    @include('partials.flash-messages')

    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <h1>Post</h1>
        <div class="container">
            @include('partials.post_partial')
        </div>
        @include('partials.comments_partial')
    </div>
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('js/datatables.js') }}"></script>
@endsection